### ISSUE TITLE
add RSS feed output format

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#124]
I'd love to be able to use Granary to generate a podcast feed from an h-feed instead of having to do that myself! Some examples that would make great podcast feeds:

* https://martymcgui.re/tag/this-week-indieweb-podcast/
* https://aaronparecki.com/tag/100daysofmusic

There are a few requirements for podcast feeds beyond traditional RSS feeds. It's a bit of a trick to get it right. If this sounds like it'd be doable I'd happily help document everything needed and how it could be parsed from the h-feed.

**Comment by snarfed** [comment]
hoo boy, whole new format! agreed, RSS would be a great addition.

i'm unlikely to work on it myself anytime soon, but i'd happily support anyone who wants to! adding a new format to granary is actually pretty fun and self contained, much more so than adding a whole new silo (since there's no auth etc). JSON Feed is a good example, see [`jsonfeed.py`](https://github.com/snarfed/granary/blob/master/granary/jsonfeed.py) and #107.

**Comment by jgmac1106** [comment]
+1 to this. I do wonder about the p-category and Apple requiring you to use their specific tags.

**Comment by snarfed** [comment]
shipped! feel free to try, feedback welcome.
