### ISSUE TITLE
Access source URLs in retweets?

### ISSUE THREAD

**Issue by skpy** [snarfed/granary#143]
I've recently downloaded my tweets from Twitter, and am trying to use Granary to convert them into static HTML files.

I'm basically doing this:
```
posts = json.loads(open(sys.argv[1], 'r').read())
for post in posts:
    decoded = twitter.Twitter('token', 'secret', 'smerrill').tweet_to_object(post)
    print decoded
```

For replies, I see the `inReplyTo` element in the resultant object; but retweets are simply the full text of the thing I retweeted prefixed with with the "RT @screenname ".  The screenname is linked to the root of that user's account, **not** the ID of the tweet that I am retweeting.

I see that the source JSON does contain the ID of the original tweet, so it should be possible to link to that, instead of just the user's Twitter home page.  This would preserve the fidelity of the retweets, provided that the original hasn't been deleted.

Before I get into munging the Granary object with data from the original source JSON, how hard would it be to construct a more representational retweet in Granary directly?

**Comment by skpy** [comment]
With the above loop, this gets me a link to the original tweet:
```
      print "https://twitter.com/%s/status/%s" % (post['retweeted_status']['user']['screen_name'], post['retweeted_status']['id_str'])
```

I'd like to see either the `RT` string become a link, such that it displays `<a href="<original_tweet_url>"RT</a> <a href="original_tweeter_url">@screenname</a>...` OR have the `@screenname` link point to their original tweet's URL rather than their Twitter home page.

**Comment by snarfed** [comment]
thanks for filing, and for all the details!

the short answer is, if you want HTML output, you want `microformats2.activities_to_html` or similar, not AS `content`. [check out the docs.](https://granary.readthedocs.io/en/stable/source/granary.html#granary.microformats2.activities_to_html)

try something like this inside your loop:

```py
decoded = microformats2.activities_to_html(
  [twitter.Twitter('token', 'secret', 'smerrill').tweet_to_activity(post)])
```

**Comment by skpy** [comment]
Thanks.  That gives me a full HTML document in a prescribed format.  I'd prefer to get just the bits I want, and produce my own output. Ultimately I need to create Markdown files to feed to [Hugo](http://gohugo.io/), and don't want to just slap front matter onto each generated HTML file.

Thanks for the pointer, though!  I think I can fumble my way through with `tweet_to_activity`, since it gives me what appears to be most of the raw content that I need.  Retweets have `verb: share` with a full URL to the original tweet, and replies have `content: inReplyTo`. With these, I should be able to cook up the Markdown that I need, and appropriate Hugo templates.

It would still be handy (for me, at least!) to have a slightly easier-to-consume representation of the processed data, but I understand mine might well be an edge case and not worth addressing within the library itself.  As such, I'll close this.

Thanks!

**Comment by snarfed** [comment]
understood! instead of `activities_to_html`, you could to try [`object_to_html`](https://granary.readthedocs.io/en/stable/source/granary.html#granary.microformats2.object_to_html) which generates the inner HTML object without the full document around it, or [`render_content`](https://granary.readthedocs.io/en/stable/source/granary.html#granary.microformats2.render_content), which generates the HTML for just the content. definitely look at other nearby functions and modules in the docs! they could use a bit more polish, but they should be pretty coplete. e.g you could [convert to AS2](http://granary.readthedocs.io/en/latest/source/granary.html#module-granary.as2) [or JSON Feed](http://granary.readthedocs.io/en/latest/source/granary.html#module-granary.jsonfeed) or another format if they'd be easier to work with.

and granary doesn't do Markdown right now, but https://github.com/Alir3z4/html2text/ is pretty good for that, you could try running it on granary's HTML output.

good luck!
