### ISSUE TITLE
[reddit] Is `content` the right mf2 field for a post?

### ISSUE THREAD

**Issue by jamietanna** [snarfed/granary#212]
For the title of the post, I'd expect `name` to be used, rather than `content`, as that makes it sound like it'd contain the full content for the post?

**Comment by snarfed** [comment]
hmm! i may need to defer to @stedn (and maybe also you @jamietanna!) pretty quickly here, since i don't use reddit myself, so i'm not familiar with its conventions, how posts are structured, etc.

having said that, looking at an example, https://www.reddit.com/r/softwaretesting/comments/9v4feu/blog_post_why_you_should_be_unit_testing_your/ , it looks like we're actually just not including the content in the mf2 at all? ie the _Hey folks, I've just written a post..._ text isn't in there. @stedn does that sound right?

here's an excerpt from the bridgy-hosted mf2 rendering of that post, https://brid-gy.appspot.com/post/reddit/jamietanna/9v4feu :
```html
<a class="u-url" href="https://reddit.com/r/softwaretesting/comments/9v4feu/blog_post_why_you_should_be_unit_testing_your/">https://reddit.com/r/softwaretesting/comments/9v4feu/blog_post_why_you_should_be_unit_testing_your/</a>
<a class="u-url" href="https://www.jvt.me/posts/2018/11/07/unit-test-functional-tests/"></a>

<div class="e-content p-name">
Blog Post: Why You Should Be Unit Testing Your Functional Acceptance Tests
 class="tag" href="https://www.jvt.me/posts/2018/11/07/unit-test-functional-tests/">https://www.jvt.me/posts/2018/11/07/unit-test-functional-tests/</a>
</div>
```

ah, i see, it's both content and name.

**Comment by stedn** [comment]
yeah, that's right, i'm not familiar with all of the activitystream types so just tried pattern matching some of the other ones i was seeing in bridgy.  

would this change be better: title will always go to activitystream 
 `name`, and then if there is text inside the post, that will go to `content`?

**Comment by snarfed** [comment]
> would this change be better: title will always go to activitystream
> `name`, and then if there is text inside the post, that will go to `content`?

yes! perfect.

**Comment by jamietanna** [comment]
I should have a PR raised for this shortly 👍

(Originally published at: https://www.jvt.me/mf2/2020/10/p4qjz/)
