### ISSUE TITLE
Are pre-2 microformats supported?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/granary#30]
Would be nice for all the existing content/implementations out there.

**Comment by snarfed** [comment]
true! i think mf1 is mostly supported, at least on the input side,  since mf2 is supposed to be backward compatible with mf1, so parsers should support it, including ours ([mf2py](https://github.com/tommorris/mf2py)). i've never done comprehensive testing though. i'd happily merge a PR with mf1 unit tests!

on the output side, granary doesn't currently emit mf1. we could consider it, but seems like a low priority unless we find concrete use cases that real users want.

**Comment by singpolyma** [comment]
Yeah, consuming would be my priority.

**Comment by kylewm** [comment]
IMHO this is the responsibility of https://github.com/tommorris/mf2py and is handled well enough to say "yes" and close :)
