### ISSUE TITLE
support block lists

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#40]
... both fetching them and covering then to mf2. lots of details in snarfed/bridgy#473.

first step is to catalog each silo's feature(s), API support, and link(s) to docs. twitter is the main (only) silo people like @voxpelli @kevinmarks @kylewm have been asking for so far.
- [x] twitter: can [read](https://dev.twitter.com/rest/reference/get/blocks/list) and [write](https://dev.twitter.com/rest/reference/post/blocks/create) both [blocks](https://support.twitter.com/articles/117063) (semi-private) and [mutes](https://support.twitter.com/articles/20171399) (private)
- facebook: looks like no API support for reading/writing [blocks](https://m.facebook.com/help/131930530214371)
- google+: nothing in the API [Person object reference](https://developers.google.com/+/web/api/rest/latest/people#resource-representations)
- Instagram: nothing [in the API](https://www.instagram.com/developer/endpoints/). might be scrapable, which we're doing already for photos etc, but meh.
- Flickr: [the API is big](https://www.flickr.com/services/api/), but i didn't see anything about [blocks](https://help.yahoo.com/kb/flickr-for-desktop/block-flickr-sln7464.html) or mutes. @kylewm can correct me if I'm wrong.

another first step is to nail down the AS and mf2 representations we want.

**Comment by voxpelli** [comment]
Regarding AS markup, one can expose blocking as a list of blocking and unblocking activities – but that would make it hard for clients to fully resolve the full state of things, so not really sure how to express this in AS. In mf2 I would say an extended XFN-like list with pagination rather than h-entries.

Just wanted to note this as early as possible before anyone goes down the activity representation route :)

**Comment by snarfed** [comment]
thanks @voxpelli!

granary uses AS as its common base format, so we need something there. most users will probably consume mf2, though, so I'm fine with any AS representation that works.

**Comment by snarfed** [comment]
AS2 Block activity type: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-block

i didn't see an AS1 Block activity or object type or verb.

**Comment by snarfed** [comment]
tentative proposed mf2: `ul.h-blocklist` of `li.h-card`s.

based on http://microformats.org/wiki/block-list-brainstorming#simple_container_of_hCards

(the `ul` could also have `h-feed`, but that may be redundant, and also the mf2 wiki says it's just for entries: http://microformats.org/wiki/h-feed )

**Comment by voxpelli** [comment]
Small note on markup of this: It makes sense I think to have a format that allows for creation and modification of blocks over Micropub and that means that a block entity in itself needs to convey that it is a blocking of something and not just have that be conveyed through the context in which it exists, such as a list of h-card getting the meaning of blocking something by being part of a h-blocklist rather than them being a h-block or some other property of an individual block.

**Comment by snarfed** [comment]
ok, granary now fetches and converts twitter blocklists. no explicit mf2 yet, just a list of `h-cards`, but it works.

**Comment by snarfed** [comment]
sounds like we're nixing the explicit `ul.h-blocklist` of `li.h-card` mf2: https://chat.indieweb.org/dev/2017-07-24#t1500935161410000

...which means this is done! closing.
