### ISSUE TITLE
Converting "post" activities to microformats2 loses content

### ISSUE THREAD

**Issue by kylewm** [snarfed/granary#44]
Moved over from https://github.com/snarfed/ownyourresponses/issues/1

Calling `microformats2.object_to_json` on a "verb": "post" *activity* drops "content" and "in-reply-to". (See previous issue for example)

I think we've missed this because activitystreams.py calls `microformats2.object_to_json` directly on `activity["object"]` (which works for notes but is lossy for likes and shares)

It also occurs to me that https://github.com/snarfed/granary/commit/2d8510d57d24a5ce15437e3ef47aafd4869fefbc was the wrong solution -- instead of passing the `activity["object"]` and `activity["context"]`, we should always pass `activity` to object_to_json, if we can.

**Comment by snarfed** [comment]
right, that makes sense. we need that inner object for pretty much everything *except* original posts, so to tighten up this representation and make it more correct, we'd want to rename `object_to_json` to `activity_to_json` and always pass the activity. there may be a few catches to porting all callers, since iirc maybe one or two don't have the activity handy, but we can figure that out.

**Comment by snarfed** [comment]
hah. i just noticed that ownyourresponses uses an old pre-granary activitystreams-unofficial module from february. sooooo yeah, we probably shouldn't pay too much attention to that part of it. :P a first step might be to update ownyourresponses to use granary in a virtualenv. :P

**Comment by kylewm** [comment]
I did do that, but honestly what I want ownyourresponses to do is 
different enough from what you want it to do, that it's probably not 
worth trying to merge my changes in.

I'm really impressed with how little code ownyourresponses has in it, by 
the way.

**Comment by kylewm** [comment]
fixed in #47
